### ISSUE TITLE
Adding Custom Field Support

### ISSUE THREAD

**Issue by admbradford** [studiopress/genesis-simple-share#70]
Hey there, I just created a quick patch to allow for custom fields inside simple share. Basically allows a user to define a specific image and description per social network. This was in response to 

http://www.studiopress.com/forums/topic/genesis-simple-share-pinterest-button/#post-183826

[Patch File](https://github.com/copyblogger/genesis-simple-share/files/223849/patch.txt)

**Comment by NicktheGeek** [comment]
@admbradford thanks! I am not sure I want to muddy the usage by blanket including the additional fields but will consider it.

I think a better solution might be to make it more extensible with custom hooks and filters. This way it isn't about plugin in a specific solution but making it usable in many solutions. I'd be happy to include that kind of change.

Also, would you consider doing a pull request? That makes it much cleaner to review and merge.

Again, thanks for the work on this and helping out in the forum!
