### ISSUE TITLE
Replace "StumbleUpon" sharing feature with "Mix"

### ISSUE THREAD

**Issue by swa433** [studiopress/genesis-simple-share#95]
The "StumbleUpon" ( http://www.stumbleupon.com/ ) service has moved to "MIX" ( https://mix.com/ ) and the existing "StumbleUpon" sharing button no longer works.

The button needs to be updated but it seems that MIX hasn't yet opened its API/endpoint for a public sharing button.

**Comment by nickcernis** [comment]
I sent an email to `vip@mix.com` to see:

- What share URLs / APIs are available.
- What official vector icons they offer.

If mix.com is not ready for prime time yet we could drop StumbleUpon and re-evaluate Mix in the future.

**Comment by nickcernis** [comment]
From Mix:

> 1. We do! Our share URL is https://mix.com/add?url=https://example.com 
> 2. You can find vectors of our logo here - https://www.dropbox.com/sh/tp26a5cu0109rb9/AAAc6-x06cGezUASpYE2xbHsa?dl=0
>
> We're still building out our share API. We have our own badge available [here](https://community.mix.com/blog/2018/7/12/add-a-mix-badge). The only StumbleUpon badges not currently supported are the ones that count visits to the URL, those are still in development. 

This gives us enough to move forward with a switch if we want to.

**Comment by DeanMultimedia** [comment]
So ... August of '18.

Any chance we can wake this up and see some progress?

**Comment by dreamwhisper** [comment]
StumbleUpon removed in https://github.com/studiopress/genesis-simple-share/pull/97
